MusicApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "users#new"
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true
  attr_reader :password
  before_validation :ensure_session_token
  #SPIRE

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    pass = BCrypt::Password.new(self.password_digest)
    pass.is_password?(password)
  end 

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  private
  def generate_unique_session_token
    token = SecureRandom::urlsafe_base64
    while User.exists?(session_token: token)
      token = SecureRandom::urlsafe_base64
    end
    token
  end 
  

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user
  skip_before_action :verify_authenticity_token
  #CRRLLL

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])

  end

  def require_logged_in 
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to users_url if logged_in?
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token if logged_in?
    session[session_token] = nil
    @current_user = nil
  end


end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create 
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      render :new 
    end
  end

  def new
    @user = User.new
    render :new
  end 
  
  def destroy    
    logout
    redirect_to session_url
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(user_params)
    if user.save!
      login!(user)
      redirect_to user_url(user)
    else
      redirect_to new_session_url
    end
  end 

  def new
  end

  def show

  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>
  <body>

  <h1>Music App</h1>

  <% if logged_in? %>
    <form action="<%= session_url %>" value="POST">
    <input type="hidden" name="_method" value="DESTROY">
    <button>Logout</button>
    </form>
  <% else %>
    <a href="<%= new_user_url %>">Sign up!</a>
    </br>
    <a href="<%= session_url %>" value="POST">Sign in!</a> 
  <% end %>
    <%= yield %>
  </body>


</html>

MusicApp/app/views/users/new.html.erb
<!--  sign-up!   -->

<h2>Sign-up!</h2>

<form action="<%= users_url %>" method="POST">
	<input id="email" type="text" name="user[email]">
  <label for="email">Email</label>
	<input id="password" type="password" name="user[password]" id="">
  <label for="password">Password</label>
	<button>Submit</button>
</form>

MusicApp/app/views/users/show.html.erb
<h2>Welcome!</h2>

Your email:
<%= current_user.email %>